### ISSUE TITLE
Laden eines Straßennetzes aus einer Datei

### ISSUE THREAD

**Issue by RichardKarlFuchs** [rrickfox/traffic-sim#10]
- Straßennetze
- Autokonstellation
- Zielsetzung

**Comment by RichardKarlFuchs** [comment]
#4

**Comment by RichardKarlFuchs** [comment]
Vorschlag: Man speichert eine Liste von Knotenpunkten mit id's, man weist straßen und Kreuzungen zwei Punkte zu und jedenm Auto eine Straße. Dadurch kann man glaub ich relativ leicht Straßen finden, auf denen es weitergehen kann.
Was hältst du davon @funketh?

**Comment by funketh** [comment]
Für den 1. Sprint sollten wir nur das Laden aus einer Textdatei ansetzen, alles weitere später

**Comment by RichardKarlFuchs** [comment]
Gegebenenfalls nicht mal im ersten, sondern vielleicht erst im zweiten Sprint

**Comment by funketh** [comment]
Denke man sollte hierfür YAML nutzen: https://www.nuget.org/packages/SharpYaml/

**Comment by RichardKarlFuchs** [comment]
Stimme dir zu, habe aber keine Ahnung, wie man das installiert.

**Comment by funketh** [comment]
mithilfe des unity addons, mit dem wir auch die immutable data types hinzugefügt haben.
einfach in ner menubar von unity auf nuget gehen.

**Comment by RichardKarlFuchs** [comment]
Ich versuchs mal...

funketh <notifications@github.com> schrieb am So., 2. Feb. 2020, 22:22:

**Comment by funketh** [comment]
Muss auch nur einer machen, wenns commited ist wirds bei jedem automatisch geladen

**Comment by RichardKarlFuchs** [comment]
Daraus schließe ich, dass du es schon gemacht hast

funketh <notifications@github.com> schrieb am So., 2. Feb. 2020, 22:28:

**Comment by funketh** [comment]
nö, kann aber mal nen branch erstellen

**Comment by funketh** [comment]
Sehr zu empfehlendes Programm für das Überprüfen von YAML Dateien:
Auf [GitHub](https://github.com/adrienverge/yamllint) bzw. [Homebrew](https://formulae.brew.sh/formula/yamllint)

**Comment by funketh** [comment]
Gute Referenz für kompliziertere YAML Funktionalität: https://camel.readthedocs.io/en/latest/yamlref.html

**Comment by funketh** [comment]
Hier ist das Wiki zu unserer Library: https://github.com/aaubry/YamlDotNet/wiki/Serialization.Deserializer
(Wir nutzen ne Fork von dem Projekt, dürfte aber aufs gleiche hinauslaufen)
