### ISSUE TITLE
Datenstruktur (Sprint 1)

### ISSUE THREAD

**Issue by RichardKarlFuchs** [rrickfox/traffic-sim#14]
- Punkte haben Koordinaten
- Straßen haben zwei Punkte
- T-Kreuzungen haben drei Straßen und drei Punkte
- Kreuzungen haben 4 straßen und 4 Punkte
- Kreisverkehre haben beliebig viele Punkte und genauso viele Straßen

**Comment by RichardKarlFuchs** [comment]
#13

**Comment by RichardKarlFuchs** [comment]
Warum müssen Nodes die Anzahl der Ankommenden bzw. Abgehenden Spuren speichern? Eigentlich sollte das aus den Straßen ersichtlich sein...

**Comment by funketh** [comment]
Notizen für die Diskussion am 17.01.

- Kreuzungen: Schienen mit Weichen (Autos checken, ob Schiene vor ihnen frei ist)
Weichenauswahl durch gewünschten Pfad des Autos eindeutig bestimmt
- Fürs Pathfinding [#9] sollte jeder Schienenursprung/-ende = Straßenspurenursprung/-ende = 1 Node
- 1 Straße = 1 dicke Kante, die mehrere Nodes mit genauso vielen Nodes verbindet und auf der man sich (durch Regeln beschränkt) frei bewegen kann
    - => Auto versucht entsprechend seines gewünschten Pfads auf der Straße eine der nächsten Nodes anzupeilen, die eine Schiene zur nächsten gewünschten Node hat.
    - Falls dies nicht gelingt, wird die Route an der Kreuzung entsprechend der Schienen, die wählbar sind, neu gewählt.

**Comment by funketh** [comment]
Diskussion in #16 ergibt:
- Anchor verbinden stets eine Straße mit einem Vertex
- Merges und Splits müssen durch Vertices symbolisiert werden

**Comment by funketh** [comment]
TODO: Einschränkung der Abbiegrichtungen der Lanes der Anchors, welche an TeeSection grenzen. (nicht im 1. Sprint relevant)
