### ISSUE TITLE
Kreisverkehr

### ISSUE THREAD

**Issue by funketh** [rrickfox/traffic-sim#2]
3f9d732

Denke man braucht zum erstellen eines kreisverkehrs nur die Info, wo die Ein-/Ausfahrten sein sollten (und welche Krümmung alle Kurven haben [#1]).
Dann sollten die T-Kreuzungen dort automatisch erstellt werden und durch entsprechende gekurvte Straßen verbunden werden.

**Comment by RichardKarlFuchs** [comment]
Ein Kreisverkehr sollte die Möglichkeit haben drei Ausfahrten zu haben.

**Comment by funketh** [comment]
Hatte gedacht man könnte die Felder entsprechend auf `null` setzten, aber
seperate Klassen erscheinen mir jetzt doch sinnvoller.

**Comment by RichardKarlFuchs** [comment]
Vielleicht wäre eine Art Array für Ein/Ausfahrten auch sinnvoll.

**Comment by funketh** [comment]
Ist wahrscheinlich die beste Option

**Comment by RichardKarlFuchs** [comment]
#5
