### ISSUE TITLE
Milestones statt Projects?

### ISSUE THREAD

**Issue by funketh** [rrickfox/traffic-sim#21]
https://stackoverflow.com/a/39701381
Wirkt auf mich so, als würden Milestones besser in unseren Scrum-Workflow passen.
@rrickfox

**Comment by RichardKarlFuchs** [comment]
Da wir relativ ungenaue Issues gesetzt haben, fand ich, dass ein project besser passt. Theoretisch ist es ja so, dass Issues eine gewisse Priorität haben und nur für einen bestimmten Sprint gelten. Da ich aber damit gerechnet habe, dass wir nicht alle issues in einem Sprint fertig kriegen, ist es leichter ein Project anzulegen. Außerdem hat man da eine bessere Visualisierung und sieht, wie weit man ist.

**Comment by funketh** [comment]
Ich denke wir sollten allgemein die **Issues kleiner und zielgerichteter ansetzen** (nicht sowas wie "Datenstruktur"), ganz egal ob wir jetzt Milestones oder Projects nutzen.
Der Sinn von Issues ist ja auch, dass man sie irgendwann schließen kann, was bei Issues wie Datenstruktur eigentlich nie passieren wird.

Kann nur für mich sprechen, aber ich habe bis jetzt noch nie wirklich den Project Tab wirklich genutzt, sondern mir eher die Issues im Issues Tab direkt angeschaut, da mir die Mischung von Issues und Pull Requests etwas unübersichtlich ist, zumal ich gerne alle offenen Issues auf einmal sehe. Und für diesen Workflow funktionieren Milestones halt besser.

Werde jetzt mal versuchen mich umzugewöhnen und schauen, ob ich den Sinn erkenne.

**Comment by domiblack** [comment]
Das sehe ich genauso wie funketh !
