### ISSUE TITLE
Nur squash merging erlauben

### ISSUE THREAD

**Issue by funketh** [rrickfox/traffic-sim#22]
@rrickfox 
Erlaube in den einstellungen mal nur squash merging
https://help.github.com/en/github/administering-a-repository/configuring-commit-squashing-for-pull-requests

**Comment by RichardKarlFuchs** [comment]
Ist bereits erlaubt

**Comment by funketh** [comment]
Ich meinte, dass die anderen methoden verboten werden (rebase & normales mergen)
