### ISSUE TITLE
access section from anchor

### ISSUE THREAD

**Issue by RichardKarlFuchs** [rrickfox/traffic-sim#26]

**Comment by funketh** [comment]
Diskussion mit @Shafma ergab, dass es einige generelle Konflikte zwischen den Anforderungen an die Datenstruktur seitens des Pathfindings (#9) und seitens der graphischen Umsetzung gibt.

**Comment by RichardKarlFuchs** [comment]
Was wäre denn ein Beispiel für diese Konflikte?

funketh <notifications@github.com> schrieb am Di., 21. Jan. 2020, 22:43:

**Comment by Shafma** [comment]
Die Anchor sind zwar schön, aber für's Pathfinding (#9) relativ ungünstig und beinhalten Redundanzen (siehe dieses Issue). Außerdem machen wir uns Sorgen um eventuelle Implikationen für die Implementierung von Einbahnstraßen, die das gesamte Konzept des Graphen sprengen.

**Comment by funketh** [comment]
Bild zum Problem [hier](https://imgur.com/VfR8NdQ) und [hier](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
EDIT: und [hier](https://www.gnu.org/) bzw. [hier](https://www.fsf.org/)

**Comment by RichardKarlFuchs** [comment]
Ich sehe das Problem der Redundanzen, allerdings nicht die unnutzbarkeit
für das Pathfinding und das Problem der Einbahnstraßen. Bei denen wäre es
ja eben genau gut zu wissen, wie viele Spuren es im Anchor gibt...

Shafma <notifications@github.com> schrieb am Di., 21. Jan. 2020, 22:49:

**Comment by funketh** [comment]
Erstmal ne Feststellung: Anchors sind eklig, weil sie in beide Richtungen
funktionieren müssen

Dann:
Die Probleme liegen beim Pathfinding. Für das Pathfinding ist die Kreuzung
1 Knoten und jede Straße 1 *ungerichtete* Kante. D.h. es gibt bei
Einbahnstraßen keinen Weg zu wissen, ob die Straße nur zur Kreuzung
hinführt oder nur von ihr wegführt. Es wird immer angenommen, das beides
geht.

Die Lösung wäre offensichtlicherweise, dass man pro Straße in beide
Richtungen ne *gerichtete* Kante unabhängig voneinander speichert, aber bei
Einbahnstraßen halt stattdessen nur 1 gerichtete Kante nutzt.
Das Problem wäre dabei, dass die Straße in der Simulation als eine einzige
angezeigt werden soll.

Unsere Idee wäre dann gewesen, dass man immer 2 entgegengesetzte Kanten,
die nebeneinander sind, (oder im Falle der Einbahnstraße nur 1 Kante)
nochmal zusätzlich in einem Straßenobjekt zusammenfasst. Dieses Objekt
würde sich dann nur um das graphische Anzeigen als einheitlich Straße
kümmern und würde dazu noch die Form der Straße speichern. (Wahrscheinlich
bräuchten die Kanten dann noch ne Referenz zu ihrem Straßenobjekt, aber ist
ja auch ok)

So weit, so gut. Eine CrossSection müsste also für ihre obere Straße nur
die beiden Edges upEdgeIncoming und upEdgeOutgoing speichern.
Die gerichteten Edges müssten nur ne startingSection und ne endingSection
speichern.
Jetzt haben wir aber wieder ein Problem mit der Grafik.
Für die brauchen wir jetzt nämlich noch konkrete Punkte.
Ansatz dafür:
* Man kann ne Straße nur unter Angabe zweier Kreuzungen erstellen (+ die
Ausrichtung relativ zur Kreuzung (up, down, left, right, etc...), aber
dafür hab ich schon nen super Ansatz mit Dictionaries und enums)
* Eine Kreuzung braucht zum Erstellen nur Point objekte bzw Koordinaten
(früher brauchte sie halt anchors).
* Wenn die Kreuzung mitbekommt, dass eine Straße an ihr erstellt werden
soll, erstellt sie die Edges und überliefert diesen die Koordinaten
* (bisschen unrelated) Das Bewegen auf der Kreuzung sollte ziemlich
wortwörtlich auf Schienen verlaufen

Ich glaube ich habe das Problem mehr oder weniger beim aufschreinen schon
gelöst, muss meinen Ansatz morgen einfach mal ausprobieren.
Hauptpunk ist eigentlich, dass Anchor in der jetzigen Form abgeschafft
werden und Straßen zu 1 bis 2 entgegengerichteten Kanten werden (die
trotzdem zusätzlich fürs graphische zusammengefasst werden).

**Comment by funketh** [comment]
Ansatz, bei dem man keine Anchor braucht:
```cs
 class Road
{
    public Dictionary<Vertex, List<Lane>> startingLanes;
    protected Dictionary<Vertex, Vertex> vertices;
    public float length;
    public RoadShape shape;

    public Vertex OtherVertex(Vertex fromVertex)
    {
        return vertices[fromVertex];
    }
}
```
in `vertices` sind die mappings vertex1 => vertex2 sowie vertex2=> vertex1 enthalten.
Koordinaten fehlen noch, aber die kann man auch wie die Lanes speichern.

**Comment by RichardKarlFuchs** [comment]
Wir sollten diese Diskussion in #20 weiterführen.
