### ISSUE TITLE
Abbiegen an Kreuzungen

### ISSUE THREAD

**Issue by funketh** [rrickfox/traffic-sim#29]
- [x] Einschränkung der Abbiegrichtungen der Lanes der Anchors, welche an TeeSection grenzen

_Originally posted by @funketh in https://github.com/rrickfox/traffic-sim/issues/14#issuecomment-576053279_

**Comment by funketh** [comment]
Inwiefern ist dieser Issue noch relevant? Was ist mit #39?

**Comment by funketh** [comment]
@rrickfox, @Sidlertime ?

**Comment by Sidlertime** [comment]
Also ich denke mal wir können die als done abhaken, also sowohl die theoretische Verbindung als auch die grafische Verbindung
