### ISSUE TITLE
backlog entfernen?

### ISSUE THREAD

**Issue by funketh** [rrickfox/traffic-sim#34]
* würde stattdessen später geplante sachen immer in den nächsten sprint auf todo packen
* das project hat zu viele Spalten
* sonst muss eigtl alles was im 2. sprint geplant ist auch zum backlog im 1. hinzugefügt werden, was nervt

@rrickfox

**Comment by RichardKarlFuchs** [comment]
Hast Recht, mache ich

funketh <notifications@github.com> schrieb am Fr., 24. Jan. 2020, 00:08:

**Comment by funketh** [comment]
hab schon
