### ISSUE TITLE
develop als default branch auf GitHub einstellen?

### ISSUE THREAD

**Issue by funketh** [rrickfox/traffic-sim#36]
* nervt bisschen, dass man von der homepage des projekts immer erst den branch wechseln muss
* nervt auch, dass das default beim PR erstellen der master ist

@rrickfox

**Comment by RichardKarlFuchs** [comment]
Master ist halt standardmäßig der default branch, damit man sofort eine
funktionstüchtige Version hat, da der Master quasi alle releases enthält.
Solange wir aber noch keine releases haben, können wir den develop auch als
default setzen.

funketh <notifications@github.com> schrieb am Fr., 24. Jan. 2020, 00:23:
