### ISSUE TITLE
branch wechseln ändert nicht die aktive Szene?

### ISSUE THREAD

**Issue by funketh** [rrickfox/traffic-sim#37]
mehr so nen unity issue, aber wenn ich nen branch mit ner anderen szene checkoute und dann diese anklicke, kann ich nach dem zurückwechseln diese nicht mehr loswerden.
restarten hilft auch nicht

**Comment by RichardKarlFuchs** [comment]
Wenn der Trick mit dem "immer Unity beim checkout geschlossen haben" dabei
auch nicht funktioniert oder es schon zu spät ist, musst du die szenendatei
und ggf eine meta Datei löschen. Genauso wenn man von einem branch mit den
packages in einen branch ohne die packages wechselt.

funketh <notifications@github.com> schrieb am Fr., 24. Jan. 2020, 00:27:
