### ISSUE TITLE
Probleme mit Spawner-Objekten

### ISSUE THREAD

**Issue by Shafma** [rrickfox/traffic-sim#48]
Wie euch bestimmt schon aufgefallen ist, wenn ihr die Simulation startet, gibt es bei der Instanziierung von den Spawner-Objekten einen Error in Unity.
(z.B. _CarDespawner must be instantiated using the ScriptableObject.CreateInstance method instead of new CarDespawner._)
Zum einen ist die vorgeschlagene Änderung nicht lauffähig, da unsere Objekte Prefabs benötigen, die wir nicht in die CreateInstance-Funktion geben können.
Andererseits ist mir (und @funketh) nicht klar wieso die Klassen überhaupt die ScriptableObject-Erbung benötigen. Zuletzt verstehe ich nicht ganz wozu CarDespawner überhaupt als Objekt ausgelagert ist, weil dessen Funktionalität sehr nah an dem ist, was EndPoint.SpawnCars in Endpoint selbst macht.
#24 #12 #8

**Comment by RichardKarlFuchs** [comment]
`CarSpawner` und `CarDespawner` müssen von `ScriptableObject` erben, damit
sie die `Instatiate` bzw. `Destroy` aufrufen können. Eine reguläre Klasse
ist dazu nicht in der Lage.

Allerdings ist es durchaus möglich die `EndPoints.SpawnCars` in die
CarSpawner Klasse auszulagern, entsprechend der DespawnCars Methode.

Shafma <notifications@github.com> schrieb am Fr., 31. Jan. 2020, 01:07:

**Comment by funketh** [comment]
> `CarSpawner` und `CarDespawner` müssen von `ScriptableObject` erben, damit
sie die `Instatiate` bzw. `Destroy` aufrufen können. Eine reguläre Klasse
ist dazu nicht in der Lage.

Stimmt so nicht, hab es so eben ausprobiert. Man muss halt statt `Instantiate` `Object.Instantiate nutzen`, (was wir sogar schon redundanterweise an einer Stelle so getan hatten).
Ich erstelle mal nen pull request

**Comment by RichardKarlFuchs** [comment]
Die Frage bleibt jedoch, welchen Vorteil die nicht Vererbung hat.

**Comment by funketh** [comment]
Keine Warnings. Außerdem sollte man nicht etwas erben, wenn es nichts bringt

**Comment by RichardKarlFuchs** [comment]
Alles klar

funketh <notifications@github.com> schrieb am Fr., 31. Jan. 2020, 11:47:
