### ISSUE TITLE
Car_ai (Einbinden von Pathfinding)

### ISSUE THREAD

**Issue by RichardKarlFuchs** [rrickfox/traffic-sim#51]
- Autos haben immer eine Edge auf der sie gerade fahren und eine Spur, auf der sie am Ende dieser Edge sein möchten.
- Das Pathfinding kann beispielsweise eine Liste mit Edges und Spuren bereitstellen, woraus die nächste Edge geholt wird.
- Am Anfang kann man das eigentliche Fahren auf der Kreuzung auch weglassen und die Autos direkt an den Andang der neuen Edge teleportieren.

**Comment by funketh** [comment]
* +1 für das teleportieren

 > Das Pathfinding kann beispielsweise eine Liste mit Edges und Spuren bereitstellen, woraus die nächste Edge geholt wird.

Versteh ich nicht

**Comment by RichardKarlFuchs** [comment]
Wenn am Anfang (vor der eigentlichen Simulation) das Pathfinding die Routen
von allen Endpoints zu allen Endpoints berechnet, kann das als Liste von
Edges und zugehörigen Lanes gespeichert werden. Dabei ist gemeint, das
jeweils die Edge, auf der man sich befindet und die Spur, auf welcher man
sich befinden möchte, wenn die Edge zu Ende ist, gespeichert wird. Wenn die
car_ai dann merkt, dass sie am Ende ihrer Edge ist, nimmt sie sich das
nächste Ziel (bestehend aus Edge und zugehörige Lane) aus der Liste. Wenn
die Liste keine Elemwnte mehr hat, ist sie an ihrem Ziel angekommen und
wird am EndPoint von diesem Despawnt.

Das mit dem Teleportieren zur nächsten Edge sorgt einfach dafür, dass wir uns nicht gleich auch um die Übergänge
auf der Kreuzung kümmern müssen, sondern direkt zur nächsten Edge springen.

funketh <notifications@github.com> schrieb am Fr., 31. Jan. 2020, 12:51:

**Comment by funketh** [comment]
verstehe nicht warum das pathfinding die lanes spezifizieren sollte. Wenn man abbiegt ist es eh egal in welche spur. außerdem war doch der sinn dass der path unabhängig von den lanes ist.

**Comment by RichardKarlFuchs** [comment]
Deiner Meinung nach muss die Car_ai also selbst herausfinden, in welcher Spur sie sein muss, um richtig abbiegen zu können.

**Comment by RichardKarlFuchs** [comment]
So wie das Pathfinding im Moment implementiert ist, wird ja bloß der weg zwischen den vertices als Weg gespeichert. Das bedeutet, dass die Autos selbst noch herausfinden müssen, auf welcher Edge sie jetzt unterwegs sein müssen und welche Spur sie dafür verwenden müssen, um am Vertex richtig abbiegen zu können. Es wäre deutlich effizienter, wenn das Pathfinding die Edge und die Zugehörigen Lanes speichert, anstatt die Vertices zu speichern, die ja eigentlich für die Autos nicht relevant sind.
