### ISSUE TITLE
In Edge wird nicht das subclassen von GameObjectData genutzt

### ISSUE THREAD

**Issue by funketh** [rrickfox/traffic-sim#66]
https://github.com/rrickfox/traffic-sim/commit/c10d2731acfc7c1185dd06a88d5a534c06ef0ab5

Der base call enthielt schon aus gutem Grund den prefab.
Die Idee von GameObjectData ist, dass das game object im constructor automatisch erstellt wird.
Position und weitere Attribute können dann am gameObject bzw transform Feld geändert werden.

**Comment by RichardKarlFuchs** [comment]
Das automatische erzeugen von einem Prefab war in der Variante, in der dieser Commit erzeugt wurde, nicht möglich. In der Version, die Jp jetzt gemacht hat, ist es durchaus möglich, die ursprüngliche Funktionalität wieder herzustellen. Tatsächlich habe ich ihm bereits dazu geraten, da jetzt nicht mehr viele einzelne Instanzen des Prefab erzeugt werden, sondern ein Straßenobjekt gebogen wird.

**Comment by funketh** [comment]
https://github.com/rrickfox/traffic-sim/pull/65/commits/5059c170e89cfba88db47df1db2eb33aa558fd54
