### ISSUE TITLE
Ungenutzes Übergeben von roadPrefab in EndPoint

### ISSUE THREAD

**Issue by RichardKarlFuchs** [rrickfox/traffic-sim#67]
Benötigen EndPoints überhaupt das RoadPrefab?
Es wird im Code nicht aufgerufen, ich glaube es stammt noch aus der Zeit, als der CarSpawner die Höhe des RoadPrefabs brauchte.
Kann man das Entfernen @funketh?

**Comment by funketh** [comment]
ja, die road ist ja schon constructed
