### ISSUE TITLE
Car-AI (Autobahn)

### ISSUE THREAD

**Issue by RichardKarlFuchs** [rrickfox/traffic-sim#7]
Auto, das geradeaus fährt, ohne mit Autos vorne und hinten zu kollidieren.
- Vorne & hinten nach Autos prüfen
- Geschwindigkeitsbegrenzung
- Beschleunigen & Bremsen (realistisch)

**Comment by RichardKarlFuchs** [comment]
Anregung:
- https://www.behrisch.de/de/lehre/lvws0809/verkehr/folgemodelle1.pdf (Folie 9-15)
- https://www.ipd.kit.edu/mitarbeiter/damast/seminar/FAS2007/pdfs/FAS2007_Pavlidis_Fahrerassistenzsysteme_Ausarbeitung.pdf (Erklärt das Wiedemann Modell, Deutsch)
- http://onlinepubs.trb.org/onlinepubs/conferences/2011/RSS/3/Higgs,B.pdf (Nochmal Wiedemann mit mehr Details, Englisch)

**Comment by RichardKarlFuchs** [comment]
Die Klasse `car_ai` wird ja durch einen `simulation_controller` aufgerufen, daher braucht sie ja eigentlich keine Update Funktion. Es sollte aber möglich sein erst eine Bewegung zu planen, ohne das Auto sofort zu bewegen, damit alle Autos quasi sich gleichzeitig bewegen. Es wenn alle Autos wissen was passiert, bewegen sie sich.

**Comment by funketh** [comment]
Können nicht alle Autos `FixedUpdate` nutzen?

**Comment by RichardKarlFuchs** [comment]
Das Problem wenn man FixedUpdate nutzt ist halt, dass nicht geregelt ist, wie die Autos sich bewegen. Wenn sich Auto 1 erst bewegt, und dann erst das Auto dahinter denkt Auto 1 ständig, dass es mehr Platz hat. Deswegen finde ich, sollten erst alle Autos wissen, was sie machen und dann sich bewegen.

**Comment by funketh** [comment]
Ok, verstehe.
Relevanter Link zu dem Problem:
https://forum.unity.com/threads/is-there-some-kind-of-late-fixed-update.389006/

**Comment by funketh** [comment]
Die Kollisionserkennung (AI auf Straßen) ist bis jetzt in der Datenstruktur #14 noch nicht möglich (Straßen speichern noch nicht, welche Autos auf ihnen fahren).
Wäre es sinnvoll, dies über Unity zu machen? Sonst müsste man entweder sein eigenes Koordinatensystem machen oder bei jedem Auto jedes andere Auto auf der Straße durchgehen.

**Comment by RichardKarlFuchs** [comment]
Im Moment sind die Autos in Listen mit Straßen gegliedert, jede dieser Listen hatt dann eine Liste mit Autos. Genausogut kann man auch direkt alle Straßen die auf ihnen befindlichen Autos speichern lassen. Das macht, denke ich, keinen großen Unterschied
