### ISSUE TITLE
GUI - Auswählen einer zu ladenen Datei

### ISSUE THREAD

**Issue by funketh** [rrickfox/traffic-sim#79]
#11 

https://docs.unity3d.com/ScriptReference/EditorUtility.OpenFilePanel.html

**Comment by RichardKarlFuchs** [comment]
anderer Vorschlag: eine liste wo alle dateien im Saves ordner drin sind. Dazu ein Add button mit dem man weitere Dateien in den Ordner schieben kann.
Ein Auswahldialog geht aber eigentlich auch

**Comment by funketh** [comment]
Kann man definitiv später hinzufügen (in nem neuen Issue), aber ein Dialog reicht denke ich vorerst

**Comment by RichardKarlFuchs** [comment]
k
