### ISSUE TITLE
Car spawner

### ISSUE THREAD

**Issue by RichardKarlFuchs** [rrickfox/traffic-sim#8]
- Autos haben Wunschgeschwindigkeit, Startpunkt, Zielpunkt

**Comment by funketh** [comment]
Spawnen sollte auf `Spawnpoint`s passieren, welche ne Unterklasse von `Vertex` sind, die 1 Anchor haben.
Dies ist für das Pathfinding notwendig.
Ich schlage vor, dass Spawnpoints graphisch ähnlich wie Sackgassen aussehen (Kreis).

**Comment by RichardKarlFuchs** [comment]
Dafür muss ja erstmal die Datenstruktur germerged sein

funketh <notifications@github.com> schrieb am So., 19. Jan. 2020, 23:27:

**Comment by RichardKarlFuchs** [comment]
#18
