### ISSUE TITLE
void SetVariable() ist keine guter Namen für ne Methode die keine kein Setter von 'Variable' ist

### ISSUE THREAD

**Issue by funketh** [rrickfox/traffic-sim#84]
Sagt einem nämlich nichts außer "Irgendwas passiert mit der Variable".

Falls die Methode nur im Constructor genutzt wird wäre sowas wie `InitializeVariable()` gut.

Andernfalls sind es meist irgendwelche methoden die etwas updaten um Änderungen anderer Werte zu übernehmen. In dem Fall sollte `UpdateVariable()` genutzt werden denke ich.

**Comment by funketh** [comment]
Meine jetzt spezifisch:
```
Car.SetPosition()
EndPoint.SetWeights()
```
Außerdem wollte ich das generell ansprechen

**Comment by RichardKarlFuchs** [comment]
nunja bei `EndPoint.SetWeights()` werden die RouteProbabilities zum ersten Mal gesetzt, was einem Setter ja ziemlich gleichkommt. Dabei wäre `CalculateRouteProbabilities()` vielleicht noch passend.
`Car.SetPosition()` könnte aber in `UpdatePosition()` umbenannt werden.

**Comment by funketh** [comment]
Würde deinem ersten Punkt nicht zustimmen, Setter haben eine klare Bedeutung im Kontext von Java-ähnlichen Sprachen und akzeptieren auch immer einen Wert, zu dem die betreffende Variable gesetzt werden soll. (Mal davon abgesehen setzt die Methode nicht die weights).
`CalculateRouteProbabilities()` ist ok

**Comment by RichardKarlFuchs** [comment]
37c00bc
