### ISSUE TITLE
Probleme mit Gewichten

### ISSUE THREAD

**Issue by funketh** [rrickfox/traffic-sim#88]
- Gewichte nehmen die Sortiertheit der routingTable Keys an, obwohl Dictionaries unsortiert sind
- derzeit hat man dies nicht bemerkt, da jeder EndPoint nur zu 1 anderen EndPoint führte
- Generell ist es für #62 unschön, wenn eine gewisse Reihenfolge der Vertices angenommen wird, da man diese dann auch in der YAML Datei beachten muss
- Vorschlag: nie nach index, sondern nach Value gehen (nach Vertex)
    - d.h. in der YAML Datei würden die Gewichte für jeweils jeden anderen Vertex in nem Dictionary spezifiziert werden
    - weights wäre dann nen Dictionary<IVertex, int>
- Alternative: weights entfernen (später wollen wir eh die routen nach Gefülltheit der Straßen der Route auswählen)

**Comment by RichardKarlFuchs** [comment]
Eine Dictionary aus Vertex und Weight anzulegen halte ich prinzipiell für sinnvoll. Zu beachten ist dabei jedoch:
- Wenn nicht alle Vertices in der Dictionary auftauchen gibt es verschiedene Möglichkeiten, darauf zu reagieren:
  - Man *muss* alle Vertices im Weight aufführen
  - Alle Vertices, die nicht enthalten sind, haben ein weight von 0
  - Alle Vertices, die nicht enthalten sind, haben ein weight von 1
- CalculateCumulative und choose benötigen eine Sortierung um zu funktionieren. Dabei stellt sich die Frage ob `Dictionary.Keys` stets die selbe Liste zurückliefert.

Generell ist mir unbekannt, dass wir das auswählen der Route nach "Vollheit" der Straßen entscheiden wollen und bin der Ansicht, dass wir das Konzept der höhergewerteten Routen beibehalten sollten.
