### ISSUE TITLE
Pathfinding

### ISSUE THREAD

**Issue by RichardKarlFuchs** [rrickfox/traffic-sim#9]
- Weg von Start zu Ziel

**Comment by Shafma** [comment]
Kann es sein, dass dieses Issue derweil extrem von #10 abhängt?
Kann natürlich auch sein, dass ich dort den Umfang falsch verstehe, weil es so vage formuliert ist, aber ich glaube ohne zu wissen woran sich das Pathfinding orientieren soll, kann man hier nur schlecht anfangen.

**Comment by RichardKarlFuchs** [comment]
Vorschlag @Shafma: Anstatt Von jedem Startpunkt zu jedem Endpunkt eine Route zu suchen, kann man auch von jedem Punkt die jeweils möglichen nächsten Punkte suchen und dann einen davon mit einer gewissen wahrscheinlichkeit auswählen, welcher dann das nächste Ziel ist. Bei diesem Punkt angekommen wiederholt sich das Ganze. Wenn ich mich nicht irre sollte das die Anzahl der gespeicherten Verbindungen vermindern und es lässt sich außerdem leichter Einstellen.

Um eine Kreuzung digital nachzubauen muss man dann nur die relativen Häufigkeiten für jede Abbiegemöglichkeit feststellen, anstatt die absoluten Routen festzulegen.

**Comment by RichardKarlFuchs** [comment]
Ok habe mich anscheinend geirrt, es könnte aber trotzdem leichter zu implementieren sein...

**Comment by Shafma** [comment]
Will hier nochmal kurz festhalten, dass ich dafür bin, das nicht nach dem oberen Vorschlag von Richard zu machen, sondern tatsächlich als Pathfinding. Nicht nur scheint das der grundsätzliche Ansatz in den meisten Implementationen zu sein, es wäre auch konsistent mit unserer mikroskopischen Simulation des Verkehrs, die ja auch versucht Fahrverhalten der Autos abbzubilden.

**Comment by RichardKarlFuchs** [comment]
Alles klar

**Comment by Shafma** [comment]
Zumindest für den ersten Sprint werden Autos erstmal fest ihrer Route folgen, selbst wenn sich die Straßensituation ändert und das möglicherweise nicht mehr optimal ist.

**Comment by funketh** [comment]
Vielleicht ein Feld `private bool Vertex._isGoal` hinzufügen (anderes Wort als goal wahrscheinlich)?
Wäre dann nen optionaler Parameter im `Vertex` constructor mit dem default Wert `false`.
Unterklassen wie Spawnpoints könnten dieses Feld auf `true` setzen, um zu signalisieren, dass das Pathfinding hier anfangen/enden kann.
https://github.com/rrickfox/traffic-sim/blob/b36b79511fab5818cb34080dd6b484ed562b8f52/Assets/Scripts/DataTypes/Vertices/Vertex.cs#L4-L15

**Comment by konstibob** [comment]
Was ist der derzeitige Stand des Entwurfes?
