### ISSUE TITLE
GUI - Wirkungsloses Warning zu DontDestroyOnLoad

### ISSUE THREAD

**Issue by funketh** [rrickfox/traffic-sim#91]
In `MusicController.Start()` wird das MusicController GameObject als DontDestroyOnLoad gesetzt, damit es beim Szenenwechsel nicht despawned.
Dabei entsteht dieses Warning:
```cs
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
UnityEngine.Object:DontDestroyOnLoad(Object)
Music.MusicController:Start() (at Assets/Scripts/Music/MusicController.cs:12)
```
Es scheint jedoch keinerlei Auswirkungen auf die Fuhnktionalität zu haben.
Außerdem ist MusicController ein root GameObject.

**Comment by RichardKarlFuchs** [comment]
MusicController wird außerdem dupliziert, wenn man in das Hauptmenü zurückkehrt
